---
title: "STAT100 at NMBU - Eksam"
output: html_notebook
---
```{r}
sqrt(1.5- (0 *0.4 + 1 *0.3+ 2 *0.3)^2)
```
```{r}
sqrt( (8*37822500 + 8*19448100)/ (8+8-2) ) * sqrt(2/8)
```
```{r}
(0.9*4900)^2
```
```{r}
24*0.2
```
```{r}
qnorm(p=0.05, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
```
```{r}
# 14:
2.6 + (-1.65*(1.09/sqrt(45)))
2.6 - (-1.65*(1.09/sqrt(45)))
```
```{r}
# 15: 
qnorm(p=0.05, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
qnorm(p=0.1, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
```
```{r}
# 15:
( 2.6 - (-1.64*(1.6/sqrt(693))) ) - ( 2.6 + (-1.64*(1.6/sqrt(693))) )
( 2.6 - (-1.28*(1.6/sqrt(693))) ) - ( 2.6 + (-1.28*(1.6/sqrt(693))) )
```
```{r}
# 18:
280*0.85
sqrt(280*0.85*(1-0.85))
```
```{r}
# 19:
qnorm(p=0.025, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
```
```{r}
241/280 - (-1.96* (sqrt( (241/280) * (1- (241/280) ) / 280 ) ) ) 
241/280 + (-1.96* (sqrt( (241/280) * (1- (241/280) ) / 280 ) ) ) 
p = 1152
```
```{r}
#20:
(241/p - (-1.96 * sqrt( (241/p) * (1 - (241/p) ) / p )  ) )  - (241/p + (-1.96 * sqrt( (241/p) * (1 - (241/p) ) / p )  ) )
```
```{r}
#21
qnorm(p=0.05, mean = 238, sd = 6, lower.tail = TRUE, log.p = FALSE)
pnorm(q=( - 0.85)/sqrt( (241/280)*(1-(241/280) ) /280), mean = 238, sd = 6, lower.tail = FALSE, log.p = FALSE)
```
```{r}
sqrt( (16*(1.45)^2 + 21*(1.34)^2) /35 )

1.427761 * sqrt( (1/16) + (1/21) )

(40.86 - 39.81) / 0.47379

qt(p=0.05, df=35, lower.tail = TRUE)

pt(q=2.28, df=35, lower.tail = FALSE)

(40.86 - 39.81) - (-1.689572 * 0.4737909)
```
```{r}
# Dependency analysis:

# Create a contingency table:
X <- c(rep("A", 10+23+53), rep("AB", 1+2+4), rep("B", 0+2+5), rep("O", 51+13+6))
Y <- c(rep("adm", 10), rep("v", 23), rep("s",53),
       rep("adm", 1), rep("v", 2), rep("s",4),
       rep("adm", 0), rep("v", 2), rep("s",5),
       rep("adm", 6), rep("v", 13), rep("s",51))

contingency <- table(X, Y)
chisq_test <- chisq.test(contingency, correct=FALSE)
chisq_test
```
```{r}
pchisq(0.87, df=3*2, lower.tail=FALSE)
```
```{r}
# Dependency analysis:

# Create a contingency table:
X <- c(rep("0", 62+7), rep("ik", 85+16))
Y <- c(rep("r+", 62), rep("r-", 7),
       rep("r+", 85), rep("r-", 16))

contingency <- table(X, Y)
chisq_test <- chisq.test(contingency, correct=FALSE)
# chisq_test$expected
(chisq_test$observed - chisq_test$expected)^2 / chisq_test$expected
```
```{r}
#33:
0.59212*10
```
```{r}
#34
0.59212 + (qt(0.025, df=95)*0.01756)
0.59212 - (qt(0.025, df=95)*0.01756)
```
```{r}
(11.72/2)/(177.17/33)
```

